platform :android do
  lane :upload_to_internal do
    # Берём имя файла из переменной окружения, либо дефолт
    aab_file = ENV["AAB_FILE"] || "Final_Goal_Fever_1.aab"
    UI.message("➡️ Uploading AAB file: #{aab_file}")

    supply(
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"], # JSON-ключ из GitHub Secrets
      package_name: "com.finalgoalfever.game",    # твой package name
      aab: "build_output/app.aab",                # ВСЕГДА один и тот же путь
      track: "internal",
      release_status: "completed",                # релиз сразу активен
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
